name: Generate Test Video

on:
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create video
        run: |
          mkdir -p output

          ffmpeg -y \
            -f lavfi \
            -i "color=c=black:s=1080x1920:r=30:d=10" \
            -vf "drawtext=text='FAKTA PELIK #001':fontcolor=white:fontsize=70:x=(w-text_w)/2:y=700,drawtext=text='Otak manusia boleh mengenali wajah':fontcolor=white:fontsize=48:x=(w-text_w)/2:y=900" \
            -c:v libx264 \
            -pix_fmt yuv420p \
            -movflags +faststart \
            output/test-video.mp4

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/test-video.mp4
